#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sagit

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/sagit/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/sagit/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/sagit/proprietary/vendor/etc/camera/dualcamera.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dualcamera.png \
    vendor/xiaomi/sagit/proprietary/vendor/etc/camera/sagit_imx268_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sagit_imx268_chromatix.xml \
    vendor/xiaomi/sagit/proprietary/vendor/etc/camera/sagit_imx268_liteon_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sagit_imx268_liteon_chromatix.xml \
    vendor/xiaomi/sagit/proprietary/vendor/etc/camera/sagit_imx386_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sagit_imx386_semco_chromatix.xml \
    vendor/xiaomi/sagit/proprietary/vendor/etc/camera/sagit_s5k3m3_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sagit_s5k3m3_semco_chromatix.xml \
    vendor/xiaomi/sagit/proprietary/vendor/etc/qdcm_calib_data_jdi_fhd_cmd_incell_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_jdi_fhd_cmd_incell_dsi_panel.xml \
    vendor/xiaomi/sagit/proprietary/vendor/etc/qdcm_calib_data_lgd_fhd_cmd_incell_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_lgd_fhd_cmd_incell_dsi_panel.xml \
    vendor/xiaomi/sagit/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/sagit/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/sagit/proprietary/vendor/etc/thermal-engine-8998-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8998-high.conf \
    vendor/xiaomi/sagit/proprietary/vendor/etc/thermal-engine-8998.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8998.conf \
    vendor/xiaomi/sagit/proprietary/vendor/firmware/tfa98xx_aac.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx_aac.cnt \
    vendor/xiaomi/sagit/proprietary/vendor/firmware/tfa98xx_ssi.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx_ssi.cnt

PRODUCT_PACKAGES += \
    libactuator_ak7371 \
    libactuator_ak7371_s5k3m3_semco \
    libchromatix_imx268_4k_preview_3a \
    libchromatix_imx268_4k_video_3a \
    libchromatix_imx268_common \
    libchromatix_imx268_cpp_hfr_120 \
    libchromatix_imx268_cpp_hfr_60 \
    libchromatix_imx268_cpp_hfr_90 \
    libchromatix_imx268_cpp_liveshot \
    libchromatix_imx268_cpp_preview \
    libchromatix_imx268_cpp_snapshot \
    libchromatix_imx268_cpp_video \
    libchromatix_imx268_cpp_video_4k \
    libchromatix_imx268_default_preview_3a \
    libchromatix_imx268_default_video \
    libchromatix_imx268_default_video_3a \
    libchromatix_imx268_hfr_120 \
    libchromatix_imx268_hfr_120_3a \
    libchromatix_imx268_hfr_60 \
    libchromatix_imx268_hfr_60_3a \
    libchromatix_imx268_hfr_90 \
    libchromatix_imx268_hfr_90_3a \
    libchromatix_imx268_liveshot \
    libchromatix_imx268_postproc \
    libchromatix_imx268_preview \
    libchromatix_imx268_snapshot \
    libchromatix_imx268_video_4k \
    libchromatix_imx268_zsl_preview_3a \
    libchromatix_imx268_zsl_video_3a \
    libchromatix_s5k3m3_semco_1080p_preview_ad5816g \
    libchromatix_s5k3m3_semco_1080p_video_ad5816g \
    libchromatix_s5k3m3_semco_4k_preview_ad5816g \
    libchromatix_s5k3m3_semco_4k_video_ad5816g \
    libchromatix_s5k3m3_semco_common \
    libchromatix_s5k3m3_semco_cpp_hfr_120 \
    libchromatix_s5k3m3_semco_cpp_hfr_60 \
    libchromatix_s5k3m3_semco_cpp_hfr_90 \
    libchromatix_s5k3m3_semco_cpp_liveshot \
    libchromatix_s5k3m3_semco_cpp_preview \
    libchromatix_s5k3m3_semco_cpp_snapshot \
    libchromatix_s5k3m3_semco_cpp_snapshot_downscale \
    libchromatix_s5k3m3_semco_cpp_snapshot_upscale \
    libchromatix_s5k3m3_semco_cpp_video \
    libchromatix_s5k3m3_semco_cpp_video_4k \
    libchromatix_s5k3m3_semco_default_preview_ad5816g \
    libchromatix_s5k3m3_semco_default_video \
    libchromatix_s5k3m3_semco_default_video_ad5816g \
    libchromatix_s5k3m3_semco_hfr_120 \
    libchromatix_s5k3m3_semco_hfr_120_ad5816g \
    libchromatix_s5k3m3_semco_hfr_60 \
    libchromatix_s5k3m3_semco_hfr_60_ad5816g \
    libchromatix_s5k3m3_semco_hfr_90 \
    libchromatix_s5k3m3_semco_hfr_90_ad5816g \
    libchromatix_s5k3m3_semco_liveshot \
    libchromatix_s5k3m3_semco_postproc \
    libchromatix_s5k3m3_semco_preview \
    libchromatix_s5k3m3_semco_snapshot \
    libchromatix_s5k3m3_semco_video_4k \
    libchromatix_s5k3m3_semco_zsl_preview_ad5816g \
    libchromatix_s5k3m3_semco_zsl_video_ad5816g \
    libchromatix_sagit_imx268_liteon_4k_preview_3a \
    libchromatix_sagit_imx268_liteon_4k_video_3a \
    libchromatix_sagit_imx268_liteon_common \
    libchromatix_sagit_imx268_liteon_cpp_hfr_120 \
    libchromatix_sagit_imx268_liteon_cpp_hfr_60 \
    libchromatix_sagit_imx268_liteon_cpp_hfr_90 \
    libchromatix_sagit_imx268_liteon_cpp_liveshot \
    libchromatix_sagit_imx268_liteon_cpp_preview \
    libchromatix_sagit_imx268_liteon_cpp_snapshot \
    libchromatix_sagit_imx268_liteon_cpp_video \
    libchromatix_sagit_imx268_liteon_cpp_video_4k \
    libchromatix_sagit_imx268_liteon_default_preview_3a \
    libchromatix_sagit_imx268_liteon_default_video \
    libchromatix_sagit_imx268_liteon_default_video_3a \
    libchromatix_sagit_imx268_liteon_hfr_120 \
    libchromatix_sagit_imx268_liteon_hfr_120_3a \
    libchromatix_sagit_imx268_liteon_hfr_60 \
    libchromatix_sagit_imx268_liteon_hfr_60_3a \
    libchromatix_sagit_imx268_liteon_hfr_90 \
    libchromatix_sagit_imx268_liteon_hfr_90_3a \
    libchromatix_sagit_imx268_liteon_liveshot \
    libchromatix_sagit_imx268_liteon_postproc \
    libchromatix_sagit_imx268_liteon_preview \
    libchromatix_sagit_imx268_liteon_snapshot \
    libchromatix_sagit_imx268_liteon_video_4k \
    libchromatix_sagit_imx268_liteon_zsl_preview_3a \
    libchromatix_sagit_imx268_liteon_zsl_video_3a \
    libchromatix_sagit_imx386_semco_4K_preview \
    libchromatix_sagit_imx386_semco_4K_video \
    libchromatix_sagit_imx386_semco_common \
    libchromatix_sagit_imx386_semco_cpp_hfr_120 \
    libchromatix_sagit_imx386_semco_cpp_hfr_60 \
    libchromatix_sagit_imx386_semco_cpp_hfr_90 \
    libchromatix_sagit_imx386_semco_cpp_liveshot \
    libchromatix_sagit_imx386_semco_cpp_preview \
    libchromatix_sagit_imx386_semco_cpp_snapshot \
    libchromatix_sagit_imx386_semco_cpp_snapshot_hdr \
    libchromatix_sagit_imx386_semco_cpp_snapshot_hht \
    libchromatix_sagit_imx386_semco_cpp_video \
    libchromatix_sagit_imx386_semco_cpp_video_hdr \
    libchromatix_sagit_imx386_semco_default_preview \
    libchromatix_sagit_imx386_semco_default_video \
    libchromatix_sagit_imx386_semco_hdr_snapshot_3a \
    libchromatix_sagit_imx386_semco_hdr_video_3a \
    libchromatix_sagit_imx386_semco_hfr_120 \
    libchromatix_sagit_imx386_semco_hfr_120_3a \
    libchromatix_sagit_imx386_semco_hfr_60 \
    libchromatix_sagit_imx386_semco_hfr_60_3a \
    libchromatix_sagit_imx386_semco_hfr_90 \
    libchromatix_sagit_imx386_semco_hfr_90_3a \
    libchromatix_sagit_imx386_semco_liveshot \
    libchromatix_sagit_imx386_semco_postproc \
    libchromatix_sagit_imx386_semco_preview \
    libchromatix_sagit_imx386_semco_snapshot \
    libchromatix_sagit_imx386_semco_snapshot_hdr \
    libchromatix_sagit_imx386_semco_video \
    libchromatix_sagit_imx386_semco_video_hdr \
    libchromatix_sagit_imx386_semco_zsl_preview \
    libchromatix_sagit_imx386_semco_zsl_video \
    libmmcamera_imx268 \
    libmmcamera_imx386_semco \
    libmmcamera_s5k3m3_semco \
    libmmcamera_sagit_imx268_liteon \
    libmmcamera_sagit_imx268_liteon_eeprom \
    libmmcamera_sagit_imx268_primax_eeprom \
    libmmcamera_sagit_imx386_semco_eeprom \
    libmmcamera_sagit_s5k3m3_semco_eeprom \
    consumerir.msm8998 \
    fingerprint.fpc.msm8998 \
    fingerprint.goodix.msm8998 \
    libgf_ca \
    libgf_hal
